BubuTech/src/Entity/Oferta.php
<?php

namespace App\Entity;

use App\Repository\OfertaRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OfertaRepository::class)]
class Oferta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $Monto = null;

    #[ORM\Column]
    private ?\DateTime $Fecha = null;

    #[ORM\ManyToOne(inversedBy: 'Ofertaa')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $ofertante = null;

    #[ORM\ManyToOne(inversedBy: 'Oferta')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Subasta $subasta = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonto(): ?float
    {
        return $this->Monto;
    }

    public function setMonto(float $Monto): static
    {
        $this->Monto = $Monto;

        return $this;
    }

    public function getFecha(): ?\DateTime
    {
        return $this->Fecha;
    }

    public function setFecha(\DateTime $Fecha): static
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    public function getOfertante(): ?Usuario
    {
        return $this->ofertante;
    }

    public function setOfertante(?Usuario $ofertante): static
    {
        $this->ofertante = $ofertante;

        return $this;
    }

    public function getSubasta(): ?Subasta
    {
        return $this->subasta;
    }

    public function setSubasta(?Subasta $subasta): static
    {
        $this->subasta = $subasta;

        return $this;
    }
}

BubuTech/src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 150)]
    private ?string $Descripcion = null;

    #[ORM\Column(length: 100)]
    private ?string $Imagen = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): static
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->Imagen;
    }

    public function setImagen(string $Imagen): static
    {
        $this->Imagen = $Imagen;

        return $this;
    }
}

BubuTech/src/Entity/Subasta.php
<?php

namespace App\Entity;

use App\Entity\Usuario;
use App\Enum\EstadoSubasta;
use App\Repository\SubastaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubastaRepository::class)]
class Subasta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $OfertaParcialGanadora = null;

    #[ORM\Column]
    private ?float $OfertaFinalGanadora = null;

    #[ORM\Column]
    private ?\DateTime $Duracion = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $Categoria = null;

    #[ORM\Column]
    private ?float $PrecioBase = null;

    #[ORM\Column(enumType: EstadoSubasta::class)]
    private ?EstadoSubasta $Estado = null;

    /**
     * @var Collection<int, Oferta>
     */
    #[ORM\OneToMany(targetEntity: Oferta::class, mappedBy: 'subasta', orphanRemoval: true)]
    private Collection $Oferta;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Producto $producto = null;

    /**
     * @var Collection<int, Comentario>
     */
    #[ORM\OneToMany(targetEntity: Comentario::class, mappedBy: 'subasta', orphanRemoval: true)]
    private Collection $Comentario;

    
    #[ORM\ManyToOne(targetEntity: Usuario::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $vendedor = null;

    #[ORM\ManyToOne(targetEntity: Usuario::class)]
    #[ORM\JoinColumn(nullable: true)]
    private ?Usuario $ganador = null;

    public function __construct()
    {
        $this->Oferta = new ArrayCollection();
        $this->Comentario = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOfertaParcialGanadora(): ?float
    {
        return $this->OfertaParcialGanadora;
    }

    public function setOfertaParcialGanadora(float $OfertaParcialGanadora): static
    {
        $this->OfertaParcialGanadora = $OfertaParcialGanadora;

        return $this;
    }

    public function getOfertaFinalGanadora(): ?float
    {
        return $this->OfertaFinalGanadora;
    }

    public function setOfertaFinalGanadora(float $OfertaFinalGanadora): static
    {
        $this->OfertaFinalGanadora = $OfertaFinalGanadora;

        return $this;
    }

    public function getDuracion(): ?\DateTime
    {
        return $this->Duracion;
    }

    public function setDuracion(\DateTime $Duracion): static
    {
        $this->Duracion = $Duracion;

        return $this;
    }

    public function getCategoria(): ?string
    {
        return $this->Categoria;
    }

    public function setCategoria(?string $Categoria): static
    {
        $this->Categoria = $Categoria;

        return $this;
    }

    public function getPrecioBase(): ?float
    {
        return $this->PrecioBase;
    }

    public function setPrecioBase(float $PrecioBase): static
    {
        $this->PrecioBase = $PrecioBase;

        return $this;
    }

    public function getEstado(): ?EstadoSubasta
    {
        return $this->Estado;
    }

    public function setEstado(EstadoSubasta $Estado): static
    {
        $this->Estado = $Estado;

        return $this;
    }

    /**
     * @return Collection<int, Oferta>
     */
    public function getOferta(): Collection
    {
        return $this->Oferta;
    }

    public function addOfertum(Oferta $ofertum): static
    {
        if (!$this->Oferta->contains($ofertum)) {
            $this->Oferta->add($ofertum);
            $ofertum->setSubasta($this);
        }

        return $this;
    }

    public function removeOfertum(Oferta $ofertum): static
    {
        if ($this->Oferta->removeElement($ofertum)) {
            // set the owning side to null (unless already changed)
            if ($ofertum->getSubasta() === $this) {
                $ofertum->setSubasta(null);
            }
        }

        return $this;
    }

    public function getProducto(): ?Producto
    {
        return $this->producto;
    }

    public function setProducto(Producto $producto): static
    {
        $this->producto = $producto;

        return $this;
    }

    /**
     * @return Collection<int, Comentario>
     */
    public function getComentario(): Collection
    {
        return $this->Comentario;
    }

    public function addComentario(Comentario $comentario): static
    {
        if (!$this->Comentario->contains($comentario)) {
            $this->Comentario->add($comentario);
            $comentario->setSubasta($this);
        }

        return $this;
    }

    public function removeComentario(Comentario $comentario): static
    {
        if ($this->Comentario->removeElement($comentario)) {
            // set the owning side to null (unless already changed)
            if ($comentario->getSubasta() === $this) {
                $comentario->setSubasta(null);
            }
        }

        return $this;
    }

    public function getVendedor(): ?Usuario
    {
        return $this->vendedor;
    }

    public function setVendedor(?Usuario $vendedor): static
    {
        $this->vendedor = $vendedor;
        return $this;
    }

    public function getGanador(): ?Usuario
    {
        return $this->ganador;
    }

    public function setGanador(?Usuario $ganador): static
    {
        $this->ganador = $ganador;
        return $this;
    }
}

BubuTech/src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsuarioRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_NOMBRE_USUARIO', fields: ['NombreUsuario'])]
class Usuario implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $NombreUsuario = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $NombreReal = null;

    #[ORM\Column(length: 20)]
    private ?string $Apellido = null;

    #[ORM\Column(length: 30)]
    private ?string $Email = null;

    #[ORM\Column]
    private ?\DateTime $FechaNacimiento = null;

    #[ORM\Column]
    private ?int $DNI = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $Direccion = null;

    /**
     * @var Collection<int, Oferta>
     */
    #[ORM\OneToMany(targetEntity: Oferta::class, mappedBy: 'ofertante')]
    private Collection $Oferta;

    /**
     * @var Collection<int, Comentario>
     */
    #[ORM\OneToMany(targetEntity: Comentario::class, mappedBy: 'comentador', orphanRemoval: true)]
    private Collection $Comentario;

    
    #[ORM\ManyToMany(targetEntity:Comentario::class, mappedBy:"UsuariosMeGusta")]
    
    private $comentariosMegusteados;

    #[ORM\Column]
    private ?float $dineroGanado = 0.00;

    #[ORM\Column]
    private ?int $cantSubastasGanadas = 0;

    #[ORM\Column]
    private ?float $dineroGastado = 0.00;

    #[ORM\Column]
    private ?float $subastaMasCara = 0.00;

    #[ORM\Column]
    private ?float $ultimaOferta = 0.00;

    public function __construct()
    {
        $this->Ofertaa = new ArrayCollection();
        $this->Comentario = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreUsuario(): ?string
    {
        return $this->NombreUsuario;
    }

    public function setNombreUsuario(string $NombreUsuario): static
    {
        $this->NombreUsuario = $NombreUsuario;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->NombreUsuario;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRol(string $rol): static
    {
        array_push($this->roles, $rol);

        return $this;
    }


    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getNombreReal(): ?string
    {
        return $this->NombreReal;
    }

    public function setNombreReal(string $NombreReal): static
    {
        $this->NombreReal = $NombreReal;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(string $Apellido): static
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTime
    {
        return $this->FechaNacimiento;
    }

    public function setFechaNacimiento(\DateTime $FechaNacimiento): static
    {
        $this->FechaNacimiento = $FechaNacimiento;

        return $this;
    }

    public function getDNI(): ?int
    {
        return $this->DNI;
    }

    public function setDNI(int $DNI): static
    {
        $this->DNI = $DNI;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->Direccion;
    }

    public function setDireccion(?string $Direccion): static
    {
        $this->Direccion = $Direccion;

        return $this;
    }

    /**
     * @return Collection<int, Oferta>
     */
    public function getOferta(): Collection
    {
        return $this->Oferta;
    }

    public function addOferta(Oferta $oferta): static
    {
        if (!$this->Oferta->contains($oferta)) {
            $this->Oferta->add($oferta);
            $oferta->setOfertante($this);
        }

        return $this;
    }

    public function removeOfertaa(Oferta $oferta): static
    {
        if ($this->Oferta->removeElement($oferta)) {
            // set the owning side to null (unless already changed)
            if ($oferta->getOfertante() === $this) {
                $oferta->setOfertante(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comentario>
     */
    public function getComentario(): Collection
    {
        return $this->Comentario;
    }

    public function addComentario(Comentario $comentario): static
    {
        if (!$this->Comentario->contains($comentario)) {
            $this->Comentario->add($comentario);
            $comentario->setComentador($this);
        }

        return $this;
    }

    public function removeComentario(Comentario $comentario): static
    {
        if ($this->Comentario->removeElement($comentario)) {
            // set the owning side to null (unless already changed)
            if ($comentario->getComentador() === $this) {
                $comentario->setComentador(null);
            }
        }

        return $this;
    }

    public function setDineroGanado(float $monto) {
        $this->dineroGanado=$this->dineroGanado+$monto;
        return $this;
    }

    public function getDineroGanado(): float {
        return $this->dineroGanado;
    }

    public function setDineroGastado(float $monto) {
        $this->dineroGastado=$this->dineroGastado+$monto;
        return $this;
    }

    public function getDineroGastado(): float {
        return $this->dineroGastado;
    }

    public function setCantidadSubastasGanadas(int $cantidad) {
        $this->cantSubastasGanadas=$this->cantSubastasGanadas+$cantidad;
        return $this;
    }

    public function getCantidadSubastasGanadas(): int {
        return $this->cantSubastasGanadas;
    }

    public function setSubastaMasCara(float $monto) {
        $this->subastaMasCara=$monto;
        return $this;
    }

    public function getSubastaMasCara(): float {
        return $this->subastaMasCara;
    }

    public function setUltimaOferta(float $monto) {
        $this->ultimaOferta=$this->setUltimaOferta+$monto;
        return $this;
    }

    public function getUltimaOferta(): float {
        return $this->ultimaOferta;
    }
}

BubuTech/templates/Subastas/detalle.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/detalle_subasta.css') }}">
{% endblock %}

{% block body %}
<main class="detalle-container">
    <h2 class="title">Detalle de la Subasta</h2>

    <div class="detalle-card">
        <div class="detalle-imagen">
            {% if subasta.producto.imagen %}
                <img src="{{ asset('uploads/productos/' ~ subasta.producto.imagen) }}" alt="{{ subasta.producto.nombre }}">
            {% else %}
                <img src="{{ asset('img/no-image.png') }}" alt="Sin imagen">
            {% endif %}
        </div>

        <div class="detalle-info">
            {# Mensajes flash #}
            {% for message in app.flashes('success') %}
                <div class="flash-success">{{ message }}</div>
            {% endfor %}
            {% for message in app.flashes('error') %}
                <div class="flash-error">{{ message }}</div>
            {% endfor %}
            <h3>{{ subasta.producto.nombre }}</h3>
            <p><strong>Descripción:</strong> {{ subasta.producto.descripcion }}</p>
            <p><strong>Precio Inicial:</strong> ${{ subasta.precioBase }}</p>
            <p><strong>Estado: {{ subasta.estado.value|upper }}</strong> </p>
            
            {% if subasta.estado.value == 'activa' and usuario is not same as(subasta.vendedor) %}
                <p><strong>Finaliza:</strong> {{ subasta.duracion|date('d/m/Y H:i') }}</p>
                {% if subasta.OfertaParcialGanadora == 0 %}
                    <p><strong>¡Sé la primer Oferta!</strong></p>
                {% else %}
                    <p><strong>Oferta Ganadora Hasta el Momento:</strong> {{ subasta.OfertaParcialGanadora }}$</p>
                {% endif %}
                <div class="oferta-seccion">
                <h4>Realizar una oferta</h4>
                <form method="post" action= "{{ path('ofertar', { id: subasta.id}) }}">
                    <input type="number" name="monto" step="0.01" min="1" required>
                    <button type="submit" class="btn-ofertar">Ofertar</button>
                </form>
                </div>
            {% elseif subasta.estado.value == 'activa' and usuario is same as(subasta.vendedor) %}
                <p><strong>Finaliza:</strong> {{ subasta.duracion|date('d/m/Y H:i') }}</p>
                {% if subasta.OfertaParcialGanadora == 0 %}
                    <p><strong>Sin Ofertas Aún</strong></p>
                {% else %}
                    <p><strong>Oferta Ganadora Hasta el Momento:</strong> {{ subasta.OfertaParcialGanadora }}$</p>
                {% endif %}
            {% endif %}
            {% if subasta.estado.value == 'finalizada' %}
                <p><strong>Oferta Ganadora:</strong> {{ subasta.OfertaFinalGanadora }}$</p>
                <p><strong>Ganador(a):</strong> {{ subasta.ganador.NombreUsuario }}</p>
                <p><strong>Historial de Ofertas:</strong></p>
                <div class="historial-ofertas">
                    {% for oferta in subasta.oferta %}
                        <p><strong>Usuario:</strong> {{ oferta.ofertante.NombreUsuario }}</p>
                        <p><strong>Monto Ofertado:</strong> {{ oferta.monto }}$</p>
                        <p><strong>----------------</strong></p>
                    {% endfor %}
                </div>
                
            {% endif %}

            <a href="{{ path('listar_subastas') }}" class="btn-volver">← Volver a la lista</a>
        </div>
    
    <div class="comentarios-seccion">
        <h4>Comentarios</h4>

        <form method="post" action= "{{ path('comentar', { id: subasta.id}) }}">
            <textarea name="comentario" rows="3" required></textarea>
            <button type="submit" class="btn-comentar">Comentar</button>
        </form>

        {% for message in app.flashes('success-coment') %}
                <div class="flash-success" style="margin-bottom: 5%;">{{ message }}</div>
        {% endfor %}
        {% for message in app.flashes('info') %}
                <div class="flash-success">{{ message }}</div>
        {% endfor %}
        {% for message in app.flashes('error') %}
                <div class="flash-success">{{ message }}</div>
        {% endfor %}

        <ul class="lista-comentarios">
            {% for comentario in comentarios %}
                <li>
                    <strong>{{ comentario.comentador.nombreUsuario }}</strong>
                    <small>{{ comentario.fecha|date('d/m/Y H:i') }}</small>
                    <p>{{ comentario.detalle }}</p>
                    <a href="{{ path('likear', { id: subasta.id, id_com: comentario.id }) }}" style="text-decoration: none;">
                        <span>👍 {{ comentario.cantidadLikes }}</span>
                    </a>
                {% if usuario is same as(subasta.vendedor) or usuario is same as(comentario.comentador) %}
                    <a href="{{ path('eliminar_comentario', { id: subasta.id, id_com: comentario.id }) }}" style="text-decoration: none;">
                        <span style="float: right;">❌ Eliminar</span>
                    </a>
                {% endif %}
                </li>
            {% else %}
                <li>No hay comentarios aún</li>
            {% endfor %}
        </ul>
    </div>
</main>

{% endblock %}

BubuTech/templates/Subastas/editar.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/gestion_subastas.css') }}">
{% endblock %}


{% block title %}Editar Subasta{% endblock %}

{% block body %}
<div class="container mt-4">
    <h2>Editar Subasta</h2>

    <form action="{{ path('editar_subasta', {id: subasta.id}) }}" method="post" enctype="multipart/form-data" class="mt-3">
        {% for message in app.flashes('success') %}
            <div class="flash-success">{{ message }}</div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <div class="flash-error">{{ message }}</div>
        {% endfor %}
        <div class="mb-3">
            <label class="form-label">Nombre del Producto</label>
            <input type="text" name="producto_nombre" class="form-control" value="{{ subasta.producto.nombre }}">
        </div>
        <br>
        <div class="mb-3">
            <label class="form-label">Descripción</label>
            <textarea name="producto_descripcion" class="form-control" rows="4" style="width: 500px;">{{ subasta.producto.descripcion }}</textarea>
        </div>
        <br>
        <div class="mb-3">
            <label class="form-label">Imagen (subir solo si querés reemplazar la actual)</label>
            <input type="file" name="producto_imagen" class="form-control">
            {% if subasta.producto.imagen %}
                <small class="text-muted">Imagen actual: 
                    <img src="{{ asset('uploads/productos/' ~ subasta.producto.imagen) }}" alt="{{ subasta.producto.nombre }}" style="width:20%;">
                </small>
            {% endif %}
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        <a href="{{ path('gestionar_subastas') }}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

BubuTech/templates/Subastas/gestionar.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/gestion_subastas.css') }}">
{% endblock %}

{% block title %}Gestionar Subastas{% endblock %}

{% block body %}
<div class="container mt-4">
    <h2 class="mb-4">Mis Subastas</h2>

    {% if subastas is not empty %}
        <div class="list-group">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label == 'error' ? 'danger' : (label == 'info' ? 'info' : 'success') }}" style="background: #e3f6e9;color: #1b5e20;border-left: 6px solid #2e7d32;">{{ message }}</div>
            {% endfor %}
        {% endfor %}
            {% for subasta in subastas %}
                <div class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        {% if subasta.producto.imagen %}
                            <img src="{{ asset('uploads/productos/' ~ subasta.producto.imagen) }}" alt="{{ subasta.producto.nombre }}" style="width: 10%;height: 10%;">
                        {% else %}
                            <img src="{{ asset('images/placeholder.png') }}" alt="Sin imagen">
                        {% endif %}
                        <h5>{{ subasta.producto.nombre }}</h5>
                        <p class="mb-1">
                            Precio base: ${{ subasta.precioBase }} <br>
                            Estado: <strong>{{ subasta.estado.value|upper }}</strong> <br>
                            {% if subasta.estado.value == 'activa' %}
                                Finaliza: {{ subasta.duracion|date('d/m/Y H:i') }}
                                {% if subasta.OfertaParcialGanadora == 0 %}
                                    <p><strong>Todavia no hay ofertas.</strong></p>
                                {% else %}
                                    <p><strong>Oferta Ganadora Hasta el Momento:</strong> {{ subasta.OfertaParcialGanadora }}$</p>
                                {% endif %}
                            {% endif %}
                            {% if subasta.estado.value == 'finalizada' %}
                                <p><strong>Oferta Ganadora:</strong> {{ subasta.OfertaFinalGanadora }}$</p>
                            {% endif %}
                        </p>
                    </div>
                    <div class="botones_gestion">
                        <a href="{{ path('detalle_subasta', {id: subasta.id}) }}" class="btn btn-sm btn-info">Ver Detalle</a>
                        
                        
                        {% if subasta.estado.value == 'pausada' %}
                            <a href="{{ path('reanudar_subasta', {id: subasta.id}) }}" class="btn btn-sm btn-success">Reanudar</a>
                        {% endif %}
                        
                        {% if subasta.estado.value == 'activa' %}
                        <a href="{{ path('pausar_subasta', {id: subasta.id}) }}" class="btn btn-sm btn-warning">Pausar</a>
                        {% endif %}
                        {% if subasta.estado.value != 'finalizada' %}
                        <a href="{{ path('editar_subasta', {id: subasta.id}) }}" class="btn btn-sm btn-primary">Editar</a>
                        <a href="{{ path('eliminar_subasta', {id: subasta.id}) }}" class="btn btn-sm btn-danger"
                           onclick="return confirm('¿Seguro que deseas eliminar esta subasta?');">
                           Eliminar
                        </a> 
                        <a href="{{ path('confirmar_subasta', {id: subasta.id}) }}" class="btn btn-sm btn-success" onclick="return confirm('¿Seguro que deseas confirmar esta subasta?');">Confirmar</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-info" style="display: flex; align-items: center;">
            <p style="margin: auto;">No tenes subastas creadas.</p>
        </div>
    {% endif %}
    <br>    
    <div class="bt-volver-container">
         <div class="bt-volver">
            <a href="{{ path('listar_subastas') }}">Volver al Menú</a>
        </div>
    </div>
   
</div>
{% endblock %}

BubuTech/templates/Subastas/subastas.html.twig
{% extends 'base.html.twig' %}
    {% block stylesheets %}
        {{ parent() }}    
        <link rel="stylesheet" href="{{ asset('css/subastas.css') }}">
    {% endblock %}
    {% block body %}   
        <main>
            <div class="busqueda-wrapper">
                <form method="get" action="{{ path('listar_subastas') }}" class="busqueda-header" style="float: right;">
                    <input type="text" name="q" placeholder="Buscar subastas..." value="{{ app.request.get('q') }}">
                    <button type="submit">🔍</button>
                </form>
                {% for message in app.flashes('publicada') %}
                    <div class="flash-success">{{ message }}</div>
                {% endfor %}
            </div>
            
            <h2 class="title">Lista de Subastas</h2>

            <div class="subastas">
                {% for subasta in subastas %}
                    <div class="subasta-card">
                        <div class="subasta-imagen">
                            {% if subasta.producto.imagen %}
                                <img src="{{ asset('uploads/productos/' ~ subasta.producto.imagen) }}" alt="{{ subasta.producto.nombre }}">
                            {% else %}
                                <img src="{{ asset('images/placeholder.png') }}" alt="Sin imagen">
                            {% endif %}
                        </div>
                        <div class="subasta-info">
                            <h3>{{ subasta.producto.nombre }}</h3>
                            <p class="descripcion">{{ subasta.producto.descripcion }}</p>
                            <p><strong>Precio base:</strong> ${{ subasta.precioBase }}</p>
                            <p><strong>Categoría:</strong> {{ subasta.categoria ?? 'Sin categoría' }}</p>
                            <p><strong>Estado: {{ subasta.estado.value|upper }}</strong> </p>
                            {% if subasta.estado.value == 'activa' %}
                                <p><strong>Finaliza:</strong> {{ subasta.duracion|date('d/m/Y H:i') }}</p>
                            {% endif %}
                            <a href="{{ path('detalle_subasta', {id: subasta.id}) }}" class="btn-detalle">Ver detalle</a>
                        </div>
                    </div>
                {% else %}
                    <p>No hay subastas publicadas por el momento.</p>
                {% endfor %}
            </div>
        </main>
    {% endblock %}